### ISSUE TITLE
NameError: name 'followers_count' is not defined

### ISSUE THREAD

**Issue by qyopyy** [unofficialdxnny/Spotified#2]
Traceback (most recent call last):
  File "C:\Users\qyopy\PC\Spotified-main\likes.py", line 188, in <module>
    likes_count = followers_count+1  # Replace with the actual number of followers
NameError: name 'followers_count' is not defined
Press any key to continue . . .

**Comment by unofficialdxnny** [comment]
hey so in `likes.py` towards the very end of the file you will see the below code :

```py
likes_count = followers_count+1  # Replace with the actual number of followers
new_title = f"followers | {followers_count}"
set_terminal_title(new_title)
```

replace it with the below code: 
```py
 likes_count = followers_count+1  # Replace with the actual number of followers
new_title = f"followers | {likes_count}"
set_terminal_title(new_title)
```

**Comment by unofficialdxnny** [comment]
Once solved you may close the issue, or ask any more questons regarding this error. if you run into any other issues please open a new issue
